apiVersion: v1
kind: PersistentVolume
metadata:
  name: sftp-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/sftp"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftp-pv-claim
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
